---
name: ci

on: [push]

jobs:
    build:
        runs-on: ubuntu-20.04

        strategy:
            matrix:
                phplint_version: [3.0.3]

        steps:
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Build
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                  push: false
                  tags: iermentraut/phplint:${{ matrix.phplint_version }}
                  build-args: |
                      COMPOSER_VERSION=2.1.3
                      PHPLINT_VERSION=${{ matrix.phplint_version }}
                      PHP_VERSION=7.4

    test:
        runs-on: ubuntu-20.04
        container: iermentraut/phplint:${{ matrix.phplint_version }}
        needs: build
        steps:
            - run: --version
              name: Print out version

      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: iermentraut/phplint:3.0.3
