---
name: ci

on: [push]

jobs:
    Build:
        runs-on: ubuntu-20.04

        strategy:
            matrix:
                platform: [alpine]
                phplint_version: [3.0.3, 3.0.2]

        steps:
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Build
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                  push: false
                  tags: iermentraut/phplint:${{ matrix.phplint_version }}-${{ matrix.platform }}
                  build-args: |
                      PLATFORM=${{ matrix.platform }}
                      COMPOSER_VERSION=2.1.3
                      PHPLINT_VERSION=${{ matrix.phplint_version }}
                      PHP_VERSION=8.0
                  outputs: type=docker,dest=${{ matrix.phplint_version }}-${{ matrix.platform }}.tar

            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                  name: ${{ matrix.phplint_version }}-${{ matrix.platform }}
                  path: ${{ matrix.phplint_version }}-${{ matrix.platform }}.tar
                  if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`

    Test:
        runs-on: ubuntu-20.04
        needs: build
        strategy:
            matrix:
                platform: [alpine]
                phplint_version: [3.0.3, 3.0.2]
        steps:
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Download artifact
              uses: actions/download-artifact@v2
              with:
                  name: ${{ matrix.phplint_version }}-${{ matrix.platform }}

            - name: Load and test Docker image
              run: |
                  docker load --input ${{ matrix.phplint_version }}-${{ matrix.platform }}.tar
                  docker run --rm iermentraut/phplint:${{ matrix.phplint_version }}-${{ matrix.platform }}

    Publish:
        runs-on: ubuntu-20.04
        needs: test
        strategy:
            matrix:
                platform: [alpine]
                phplint_version: [3.0.3, 3.0.2]
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v2
              with:
                  name: ${{ matrix.phplint_version }}-${{ matrix.platform }}

            - name: Load Docker image
              run: docker load --input ${{ matrix.phplint_version }}-${{ matrix.platform }}.tar

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Push images to DockerHub
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: iermentraut/phplint:${{ matrix.phplint_version }}-${{ matrix.platform }}

            - name: Double-check whether pushes to DockerHub were successful
              run: |
                  docker pull iermentraut/phplint:${{ matrix.phplint_version }}-${{ matrix.platform }}
                  docker run --rm iermentraut/phplint:${{ matrix.phplint_version }}-${{ matrix.platform }}
