---
name: ci

on:
    push:
        paths:
            - .github/**
            - Dockerfile
            - .dockerignore
            - entrypoint.sh

    pull_request:
        paths:
            - .github/**
            - Dockerfile
            - .dockerignore
            - entrypoint.sh

jobs:
    Build:
        runs-on: ubuntu-20.04

        strategy:
            matrix:
                platform: [alpine]
                phplint_version: [3.0.3, 3.0.2]

        steps:
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Build images
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                  push: false
                  tags: iermentraut/phplint:${{ matrix.phplint_version }}-alpine
                  build-args: |
                      COMPOSER_VERSION=2.1.3
                      PHPLINT_VERSION=${{ matrix.phplint_version }}
                      PHP_VERSION=8.0
                  outputs: type=docker,dest=${{ matrix.phplint_version }}-alpine.tar

            - name: Upload images as artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: ${{ matrix.phplint_version }}-alpine
                  path: ${{ matrix.phplint_version }}-alpine.tar
                  if-no-files-found: error

    Test:
        runs-on: ubuntu-20.04
        needs: [build]

        strategy:
            matrix:
                platform: [alpine]
                phplint_version: [3.0.3, 3.0.2]

        steps:
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Download artifact
              uses: actions/download-artifact@v2
              with:
                  name: ${{ matrix.phplint_version }}-alpine

            - name: Load Docker images from .tar
              run: |
                  docker load --input ${{ matrix.phplint_version }}-alpine.tar

            - name: Basic functionality test
              run: |
                  echo "<?php echo 'Hello world'; ?>" > $(pwd)/hello.php
                  docker run --rm -v $(pwd):/src iermentraut/phplint:${{ matrix.phplint_version }}-alpine
                  docker run --rm -u $UID -v $(pwd):/src iermentraut/phplint:${{ matrix.phplint_version }}-alpine

            - name: Install Grype
              run: |
                  curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

            - name: Install Trivy
              run: |
                  curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.21.0

            - name: Scan images for known vulnerabilities with Grype
              run: |
                  grype ${{ matrix.phplint_version }}-alpine.tar

            - name: Scan images for known vulnerabilities with Trivy
              run: |
                  trivy image iermentraut/phplint:${{ matrix.phplint_version }}-alpine

    Publish:
        runs-on: ubuntu-20.04
        needs: [test]
        strategy:
            matrix:
                platform: [alpine]
                phplint_version: [3.0.3, 3.0.2]
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v2
              with:
                  name: ${{ matrix.phplint_version }}-alpine

            - name: Load Docker image
              run: docker load --input ${{ matrix.phplint_version }}-alpine.tar

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Push images to DockerHub
              if: github.ref == 'refs/heads/master'
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: iermentraut/phplint:${{ matrix.phplint_version }}-alpine

            - name: Push images with SHA commit hashes to DockerHub
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: iermentraut/phplint:${{ matrix.phplint_version }}-alpine-$(GITHUB_SHA)

            - name: Double-check whether pushes to DockerHub were successful
              run: |
                  docker pull iermentraut/phplint:${{ matrix.phplint_version }}-alpine
                  docker pull iermentraut/phplint:${{ matrix.phplint_version }}-alpine-$(GITHUB_SHA)
